# Generated by Django 2.2.6 on 2019-10-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paginas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('orden', models.SmallIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('editado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paginas',
                'verbose_name_plural': 'Paginass',
                'ordering': ['orden', 'titulo'],
            },
        ),
    ]
