# Generated by Django 2.2.6 on 2019-10-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paginas',
            options={'ordering': ['orden', 'titulo'], 'verbose_name': 'Pagina', 'verbose_name_plural': 'Paginas'},
        ),
    ]
